### PR TITLE
Completed the Newsweek Clone

### PR DESCRIPTION
**Pull request by markonikovic**
For this project, I used Bootstrap, CSS-grid, flex-box and floats to position the elements on the page. The goal was to recreate the Newsweek page. I tried to use Bootstrap as much as possible. The use of semantic HTML tags was also very important for me. I feel like I have a long time to go when it comes to learning Bootstrap but I think this project really made me realize how Bootstrap can help me in my future endeavors.

### CODE REVIEW

**Comment by thsvr** [comment]
### **STATUS: CHANGES REQUIRED**

Hi @markonikovic :smile: :smile: 

**You did a great job so far and there are just a few changes to make your project looks perfect** :100: :1st_place_medal: 

Can you please take a look at the required changes and do them before your next submission? :smile_cat: 

### **REQUIRED CHANGES:**

:v: On the bigger screen, your page is scrolling instead of the components been resized. Can you please fix it?
:v: On the navbar, on the left size of it, we are supposed to also add some date. Can you please add it?

### **Optional Suggestions:**

:v:  You can create a feature branch with a more descriptive name **on the next projects**, like ''main-page'' or ''nw-page'' instead of ''feature'' or ''dev'', for example. It will be more descriptive. 

:v: It will be more appropriate if you consider adding more commits during your job, with more details about what you did. Your commits are not descriptive. Please take a look on the bullet point 3 of this link to see a good example [Descriptive Commits
](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) and also in this link [Professional Commits](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/) :+1: :+1: :+1: 

:v:  Instead of using too many <div> tags it is better (when it is possible) you use other tags like <article> inside some <section> tags  in some cases etc. 
**Please take a look at this link** →  [HTML Semantic Elements W3Schools](https://www.w3schools.com/html/html5_semantic_elements.asp) -  to check which tags can be more appropriate in different cases and consider to do few changes.



_If you have any questions, don't hesitate to contact me through slack_ [@Thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next review** :desktop_computer: :computer_mouse: 




**_Project reviewd by Thaís Vieira (TSE)_**

**Comment by markonikovic** [comment]
Thank you for your review Viera, I have created the date that appears on the big screen like on the original page, for the "fixed" effect in the main section, I really don't know how to do. I have asked my stand up team and they told me that JS is required in order to achieve such an effect. I still haven't studied JS, I am not that far in the curriculum, so please take that into consideration.

**Comment by markonikovic** [comment]
Thank you for your review Daniel, I haven't noticed horizontal scroll until you pointed out. It was caused by the second navbar that appears on big screens, I gave it relative width instead of fixed so it should be fine now.

**Comment by markonikovic** [comment]
Thank you for approving my project Daniel, I have tried making font smaller but it doesn't look too good, it looks very strange so instead, I added overflow: hidden, so it doesn't brake in another row.

**Pull request merged**
